char *help_mkfs[]={
  "Usage: kfs_mkfs [command] [options]",
  "",
  "Description:",
  "    kfs_mkfs creates a Kanek File System in a single file/device or a",
  "    group of them.",
  "",
  "General options:",
  "    -v                Verbose mode",
  "    -h                Help",
  "",
  "Commands:",
  "    kfs               Create a KFS file system in files/devices",
  "    meta              Create KFS metadata",
  "    ost               Create KFS object Storage",
  "    graph             Create KFS graph data structure",
  "",
};

char *help_mkfs_kfs[]={
  "Options for create KFS file systems:",
  "    -f kfs_file       Make a complete KFS file system in the",
  "                       specified file. If it does not exist, a -d",
  "                       option is required immediately after this",
  "                       option.",
  "    -d file_size      Specify a file with size file_size",
  "    -i inodes_num     Specify inodes_num inodes",
  "    -s slots_num      Specify slots_num metadata slots",
  "    -p percentage     Use percentage of file space for inodes and",
  "                      metadata",
  "    -w conf_file      Write conf_file for file system configuration",
  "    -x items,blocks   write out math results for required items or",
  "                      blocks",
  "",
  "",
  "    Notes:",
  "        -The option -f is mandatory.",
  "",
  "        -The optional conf_file will be written for posterior mounts",
  "         or post processing",
  "",
  "        -If -x option is specified, the items used are both super",
  "         inodes and metadata slots.",
  "         items:",
  "            If the -d is passed and/or the size detected, the number",
  "            of items and used blocks are shown.",
  "            If the -p is passed, the percentage calculations will be",
  "            shown also.",
  "",
  "            This basically shows how many items would be created with",
  "            a KFS file system, accordingly with the arguments passed.",
  "",
  "         blocks: arguments -s and -i are mandatory in this mode.",
  "            The calculations shows the number of blocks and file size",
  "            required for that number of items.",
  "",
  "        -The -p argument specified which percentage of the file will",
  "         be used for both metadata slots and super inodes. That means",
  "         if we set, let's say 10%, 5% of the available space will be",
  "         metadata slots, and 5% super inodes.",
  "",
};

char *help_mkfs_meta[]={
  "Options for create KFS metadata:",
  "    -f metadata_file  Make just a KFS metadata structure in the",
  "                        specified file. If it does not exist, a -d",
  "                        option is required, immediately after this",
  "                        option.",
  "    -d file_size      Create a file with size file_size",
  "    -s slots_num      Make slots_num metadata slots",
  "    -p percentage     Use percentage of file space for metadata",
  "    -k key            Create a hash based on the key passed",
  "    -x items,blocks   write out math results for required items or",
  "                      blocks",
  "",
  "    Notes:",
  "        -Options -f, -k are mandatory",
  "",
  "        -A not complete KFS superblock will be created in the",
  "         metadata file, if a KFS object storage or KFS file system",
  "         based on this metadata are later required. On that",
  "         situation, the passed key will also be required.",
  "",
  "        -The -k key is required, as it will be needed later on, when",
  "         KFS object storage and KFS graph are created.",
  "",
  "        -If -x option is specified, the items are metadata slots.",
  "         items:",
  "            If the -d is passed and/or the size detected, the number",
  "            of items and used blocks are shown.",
  "            If the -p is passed, the percentage calculations will be",
  "            shown also.",
  "",
  "            This basically shows how many items would be created with",
  "            a KFS file system, accordingly with the arguments passed.",
  "",
  "         blocks: arguments -s and -i are mandatory in this mode.",
  "            The calculations shows the number of blocks and file size",
  "            required for that number of items.",
  "",
  "        -The -p argument specified which percentage of the file will",
  "         be used for metadata slots.",
  "",
};

char *help_mkfs_ost[]={
  "Options for create KFS Object Storage:",
  "    -f os_file        Make just a KFS object storage structure in the",
  "                        specified file. If it does not exist, a -d",
  "                        option is required immediately after this",
  "                        option.",
  "    -d file_size      Create a file with size file_size",
  "    -m metadata_file  Use this metadata for create the object storage",
  "    -i inodes_num     Make inodes_num inodes",
  "    -p percentage     Use percentage of file space for inodes",
  "    -k key            Use key for link with the superblock in the",
  "                      metadata file",
  "    -x items,blocks   write out math results for required items or",
  "                      blocks",
  "",
  "    Notes:",
  "        -Options -f, -k, -m are mandatory",
  "",
  "        -The metadata file is required, as the relationship of the",
  "         metadata with the super inodes will be established and the",
  "         superblock in the metadata file will be updated.",
  "",
  "        -The -k key is required, as it is required for link the",
  "         object storage with an existing KFS metadata file",
  "",
  "        -If -x option is specified, the items used are super inodes.",
  "         items:",
  "            If the -d is passed and/or the size detected, the number",
  "            of items and used blocks are shown.",
  "            If the -p is passed, the percentage calculations will be",
  "            shown also.",
  "",
  "            This basically shows how many items would be created with",
  "            a KFS file system, accordingly with the arguments passed.",
  "",
  "         blocks: arguments -s and -i are mandatory in this mode.",
  "            The calculations shows the number of blocks and file size",
  "            required for that number of items.",
  "",
  "        -The -p argument specified which percentage of the file will",
  "         be used for super inodes.",
  "",
};

char *help_mkfs_graph[]={
  "Options for create KFS filesystem graph",
  "    -f graph_file     Make the graph data structure for an existing",
  "                      object storage structure, already descripted in",
  "                      the superblock stored in the specified metadata",
  "                      file.",
  "                      If the file does not exist, a -d option is",
  "                      required immediately after this option.",
  "    -d file_size      Create a file with size file_size",
  "    -m metadata_file  Use this metadata for create the object storage",
  "    -k key            Use key for link with the superblock in the",
  "                      metadata file",
  "    -w conf_file      Write conf_file for file system configuration",
  "",
  "",
  "",
  "    Notes:",
  "        -Options -f, -k, -m are mandatory",
  "",
  "        -The metadata file is required, as the relationship of the",
  "         super inodes, the metadata and the file system graph will be",
  "         established and the superblock in the metadata file will be",
  "         updated.",
  "",
  "        -The -k key is required, as it is required for link the KFS",
  "         graph with a existing object storage file and KFS metadata",
  "         file.",
  "",
  "        -The optional conf_file will be written for posterior mounts",
  "         or post processing. If not specified, a default kfsd.conf",
  "         will be created.",
  "",
};

char *help_mkfs_gennotes[]={
  "    General Notes",
  "    kfs_mkfs can build a KFS file system in the specified file",
  "       name. It includes the KFS metadata ( key and values) for",
  "       the KFS filesystem the KFS super inodes and the KFS Graph",
  "       logical structure.",
  "",
  "    kfs_mkfs may also build KFS on-disk data structures in separated",
  "       files or devices. The on-file data structures",
  "       it can build are:",
  "        -KFS metadata ( key/values)",
  "        -KFS object storage (super inodes)",
  "        -KFS graph data structure.",
  "",
  "       KFS data structures created separately should have the",
  "       same key in order to be linked together and work as a",
  "       Graph filesystem. When this happens a kfsd.conf file is",
  "       created and the KFS superblock is stored in the KFS",
  "       metadata file.",
  "",
  "       The KFS metadata and KFS super inodes files are enough to",
  "       launch have an Object Storage service.",
  "",
  "",
  "    Options works with the next conditions:",
  "      -If the file name passed in the option -f already exists and is",
  "       a regular file or a block device, the requested data structure",
  "       will be created within the file capacity.",
  "",
  "      -For the [-d fs_size] option, the expected value is the size in",
  "       MBytes. Also the characters 'M' and 'G' after the number",
  "       specifies if we refer to MBytes or GBytes. Examples:",
  "       20    20 MByes",
  "       512M  512 MBytes",
  "       8G    8 GBytes",
  "",
  "",
  "      -If -x option is specified, nothing is touched but math results",
  "       are shown, depending on the argument:",
  "       items:",
  "            If the -d is passed and/or the size detected, the number",
  "            of slots, superinodes and used blocks are shown.",
  "            If the -p is passed, the percentage calculations will be",
  "            shown also.",
  "",
  "            This basically shows how many KFS items would be created",
  "            with a KFS file system, accordingly with the arguments",
  "            passed.",
  "",
  "            The items used may be metadata slots and super inodes.",
  "            What is shown depends on what are we creating.",
  "            -If we are creating a KFS file system in a single file,",
  "             both super inodes and metadata slots are used",
  "            -If we are creating KFS metadata, only metadata slots are",
  "            used",
  "            -If we are creating KFS object storage, only super inodes",
  "            are used.",
  "",
  "       blocks: arguments -s and/or -i may be mandatory in this",
  "            mode. The calculations shows the number of blocks and",
  "            file size required for that number of items.",
  "",
  "      -If -p is specified that percentage is used for the",
  "       super inodes and/or slots. The default is about 10%.",
  "",
  "",
  "Author",
  "    Armando A. Garduno  <bsdero@gmail.com>",
  "    https://github.com/bsdero/kanenkfs",
  "",
};

